#pragma once

enum ControllerError : uint8_t
{
    CONTROL_ERR_INVALID_ENDPOINT = 100,
    CONTROL_ERR_BUFFER_EMPTY = 101,
    CONTROL_ERR_NOTHING_TODO = 102,
    CONTROL_ERR_NOT_IMPLEMENTED = 103,
    CONTROL_ERR_UNEXPECTED_DATA = 104,
    CONTROL_ERR_INVALID_ARGUMENT = 105,
    CONTROL_ERR_INVALID_REPORT_DESCRIPTOR = 106,
    CONTROL_ERR_HID_IS_NOT_JOYSTICK = 107,
};
